name: Run Backtest for Super400

on:
  workflow_dispatch: # Permite execução manual
  push: # Executa automaticamente em cada push para o branch principal
    branches:
      - main

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Passo 3: Instalar as dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy tensorflow qiskit scikit-learn joblib scipy
      
      # Passo 4: Executar o script
      - name: Run Backtest
        run: python "Super400.py"

      # Passo 5: Instalar o GitHub CLI para upload manual
      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh
          gh auth login --with-token <<< "$GITHUB_TOKEN"

      # Passo 6: Upload dos resultados
      - name: Upload Results
        run: |
          gh release create backtest-results backups/*.csv -t "Backtest Results" -n "Resultados do backtest gerados automaticamente."
