name: Backtest for Super400

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Fazer o checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Passo 2: Configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use a versão necessária do Python

    # Passo 3: Instalar dependências (se necessário)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy tensorflow qiskit scikit-learn

    # Passo 4: Executar o script e salvar os logs
    - name: Run Super400 script
      run: |
        python Super400.py | tee super400_output.log

    # Passo 5: Fazer upload dos logs como artefato
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: super400-logs
        path: super400_output.log
