name: Run Backtest for Super400

on:
  workflow_dispatch: # Permite execução manual
  push: # Executa automaticamente em cada push para o branch principal
    branches:
      - main

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Python para uma versão compatível
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Versão compatível com TensorFlow e Qiskit

      # Passo 3: Instalar as dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy==1.21.6 tensorflow==2.9.0 qiskit==0.41.0 qiskit-aer==0.11.2 scikit-learn joblib scipy
      
      # Passo 4: Executar o script
      - name: Run Backtest
        run: python "Super400.py"

      # Passo 5: Upload dos resultados do backtest
      - name: Upload Backtest Results
        uses: actions/upload-artifact@v2
        with:
          name: backtest-results
          path: |
            backups/*.csv
